apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: manager-metrics
  namespace: system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - chia-operator-system
  selector:
    matchLabels:
      control-plane: controller-manager
