# permissions for end users to edit chiaintroducers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chia-operator
    app.kubernetes.io/managed-by: kustomize
  name: chiaintroducer-editor-role
rules:
- apiGroups:
  - k8s.chia.net
  resources:
  - chiaintroducers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiaintroducers/status
  verbs:
  - get
