# permissions for end users to view chiatimelords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chiatimelord-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chia-operator
    app.kubernetes.io/part-of: chia-operator
    app.kubernetes.io/managed-by: kustomize
  name: chiatimelord-viewer-role
rules:
- apiGroups:
  - k8s.chia.net
  resources:
  - chiatimelords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiatimelords/status
  verbs:
  - get
