# This rule is not used by the project chia-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over k8s.chia.net.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chia-operator
    app.kubernetes.io/managed-by: kustomize
  name: chiacertificates-admin-role
rules:
- apiGroups:
  - k8s.chia.net
  resources:
  - chiacertificates
  verbs:
  - '*'
- apiGroups:
  - k8s.chia.net
  resources:
  - chiacertificates/status
  verbs:
  - get
