# permissions for end users to view chianetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chia-operator
    app.kubernetes.io/managed-by: kustomize
  name: chianetwork-viewer-role
rules:
- apiGroups:
  - k8s.chia.net
  resources:
  - chianetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chianetworks/status
  verbs:
  - get
