---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiacas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiacas/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiacas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiadnsintroducers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiadnsintroducers/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiadnsintroducers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiafarmers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiafarmers/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiafarmers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiaharvesters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiaharvesters/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiaharvesters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chianodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chianodes/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chianodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiatimelords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiatimelords/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiatimelords/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiawallets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiawallets/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiawallets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
