---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiacas
  - chiacertificates
  - chiacrawlers
  - chiadatalayers
  - chiafarmers
  - chiaharvesters
  - chiaintroducers
  - chianetworks
  - chianodes
  - chiaseeders
  - chiatimelords
  - chiawallets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.chia.net
  resources:
  - chiacas/finalizers
  - chiacertificates/finalizers
  - chiacrawlers/finalizers
  - chiadatalayers/finalizers
  - chiafarmers/finalizers
  - chiaharvesters/finalizers
  - chiaintroducers/finalizers
  - chianetworks/finalizers
  - chianodes/finalizers
  - chiaseeders/finalizers
  - chiatimelords/finalizers
  - chiawallets/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.chia.net
  resources:
  - chiacas/status
  - chiacertificates/status
  - chiacrawlers/status
  - chiadatalayers/status
  - chiafarmers/status
  - chiaharvesters/status
  - chiaintroducers/status
  - chianetworks/status
  - chianodes/status
  - chiaseeders/status
  - chiatimelords/status
  - chiawallets/status
  verbs:
  - get
  - patch
  - update
