apiVersion: k8s.chia.net/v1
kind: ChiaNetwork
metadata:
  labels:
    app.kubernetes.io/name: chia-operator
    app.kubernetes.io/managed-by: kustomize
  name: chianetwork-sample
spec:
  name: testnetz
  constants:
    MIN_PLOT_SIZE: 18
    GENESIS_CHALLENGE: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    GENESIS_PRE_FARM_POOL_PUZZLE_HASH: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  config:
    address_prefix: txch
    default_full_node_port: 58444
  networkPort: 58444
  introducerAddress: intro.testnetz.cluster.local
  dnsIntroducerAddress: dnsintro.testnetz.cluster.local
