apiVersion: k8s.chia.net/v1
kind: ChiaDataLayer
metadata:
  labels:
    app.kubernetes.io/name: chia-operator
    app.kubernetes.io/managed-by: kustomize
  name: chiadatalayer-sample
spec:
  chia:
    caSecretName: "chiaca-secret" # A kubernetes Secret containing certificate authority files
    # A kubernetes Secret named chiakey-secret containing a key.txt file with your mnemonic key
    secretKey:
      name: "chiakey-secret"
      key: "key.txt"
  dataLayerHTTP:
    enabled: true
