apiVersion: k8s.chia.net/v1
kind: ChiaDNSIntroducer
metadata:
  labels:
    app.kubernetes.io/name: chiadnsintroducer
    app.kubernetes.io/instance: chiadnsintroducer-sample
    app.kubernetes.io/part-of: chia-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: chia-operator
  name: chiadnsintroducer-sample
spec:
  chia:
    caSecretName: chiaca-secret
    testnet: true
    timezone: "UTC"
    logLevel: "INFO"
    bootstrapPeer: "node.default.svc.cluster.local"
    minimumHeight: 100
    domainName: "seeder.default.svc.cluster.local"
    nameserver: "dns-introducer.example.com"
    rname: "admin.example.com"
  storage:
    chiaRoot:
      claimName: "chiadnsintroducer-sample-chiaroot"
