apiVersion: k8s.chia.net/v1
kind: ChiaTimelord
metadata:
  labels:
    app.kubernetes.io/name: chiatimelord
    app.kubernetes.io/instance: chiatimelord-sample
    app.kubernetes.io/part-of: chia-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: chia-operator
  name: chiatimelord-sample
spec:
  # TODO(user): Add fields here
