apiVersion: k8s.chia.net/v1
kind: ChiaDataLayer
metadata:
  labels:
    app.kubernetes.io/name: chia-operator
    app.kubernetes.io/managed-by: kustomize
  name: chiadatalayer-sample
spec:
  # TODO(user): Add fields here
